---
dns:
  tld:
    example.com:
      - {type: 'A', name: '@',   data: 'homebase'}
      - {type: 'A', name: 'www', data: 'homebase'}
      - {type: 'A', name: 'feeds', data: 'homebase'}
      - {type: 'TXT', name: '@', data: 'google-site-verification=123' }
      - {type: 'MX', data: 'gmail' }
