---
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:
    - name: fwd | copy nginx config
      template: src=templates/fwd.j2 dest=/etc/nginx/sites-enabled/fwd
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      action: service name=nginx pattern=/etc/init.d/nginx state=restarted enabled=yes  
