---
- hosts: all
  user: $master
  sudo: false

  tasks:
    - apt: pkg=$item state=latest install_recommends=no
      with_items:
      - htop
      - mc
      - zsh
      - vim
      sudo: true
    - name: zsh | set for master
      shell: sudo chsh ${master} -s /bin/zsh
      when: zsh
    - name: dotfiles | clone
      git: repo=${dotfiles} dest=/home/${master}/dotfiles update=no
      when: dotfiles is defined
      notify:
        - Install dotfiles

  handlers:
    - name: Install dotfiles
      shell: cd ~/dotfiles/ && ./install.sh
