---
digitalocean:
    client_id: GET_ONE_AT_DIGITALOCEAN_DOT_COM
    api_key: GET_ONE_AT_DIGITALOCEAN_DOT_COM
dns:
    tld:
      example.com:
        # only A records supported so far...
        - {type: 'A', name: '@',   data: 'homebase'}
        - {type: 'A', name: 'feeds', data: 'homebase'}
        - {type: 'A', name: 'whatever', data: '8.8.8.8'}
homebase:
    master: 'your_name'
    public_host: 'example.com'
    gitolite:
      enabled: true
    fwd:
      enabled: true
      public_host: 'pseudosecrect.example.com'
    stringer:
      enabled: true
      password: 'foobar'
      postgres_user_password: MONSTER_SECRET
      public_host: 'feeds.example.com'
    jekyll:
      enabled: true
      public_host: 'blog.example.com'
      # Leave blank or remove for the default theme
      template_repo: 'https://github.com/caarlos0/up.git'
      template_branch: 'gh-pages'
    nginx:
      redirects:
        - {from: 'example.com', to: 'blog.example.com'}
        - {from: 'www.example.com', to: 'blog.example.com'}