- name: rbenv | install build depends
  apt: pkg=$item state=latest install_recommends=no
  with_items:
    - build-essential
    - git
    - libcurl4-openssl-dev
    - libreadline-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
    - libreadline-dev        

- name: rbenv | update rbenv repo
  git: repo=git://github.com/sstephenson/rbenv.git dest=$rbenv_root

- name: rbenv | add rbenv to path
  file: path=/usr/local/bin/rbenv src=${rbenv_root}/bin/rbenv state=link

- name: rbenv | add rbenv initialization to profile
  template: src=rbenv.sh.j2 dest=/etc/profile.d/rbenv.sh owner=root group=root mode=0755

- name: rbenv | check ruby-build installed
  command: test -x /usr/local/bin/ruby-build
  register: rbuild_present
  ignore_errors: yes

- name: rbenv | create temporary directory
  command: mktemp -d
  register: tempdir
  when: rbuild_present.rc == 1

- name: rbenv | clone ruby-build repo
  git: repo=git://github.com/sstephenson/ruby-build.git dest=${tempdir.stdout}/ruby-build
  when: rbuild_present.rc == 1

- name: rbenv | install ruby-build
  command: ./install.sh chdir=${tempdir.stdout}/ruby-build
  when: rbuild_present.rc == 1

- name: rbenv | remove temporary directory
  file: path=${tempdir.stdout} state=absent
  when: rbuild_present.rc == 1

- name: rbenv | check ruby $ruby_version installed
  shell: RBENV_ROOT=${rbenv_root} rbenv versions | grep $ruby_version
  register: ruby_installed
  ignore_errors: yes

- name: rbenv | install ruby $ruby_version
  shell: RBENV_ROOT=${rbenv_root} rbenv install $ruby_version
  when: not ruby_installed.stdout

- name: rbenv | set global ruby $ruby_version
  shell: RBENV_ROOT=${rbenv_root} rbenv global $ruby_version
  when: not ruby_installed.stdout

- name: rbenv | rehash
  shell: RBENV_ROOT=${rbenv_root} rbenv rehash
  when: not ruby_installed.stdout

- name: rbenv | set gemrc
  copy: src=gemrc dest=/root/.gemrc owner=root group=root mode=0644

- name: rbenv | bundler installed?
  shell: RBENV_ROOT=${rbenv_root} /usr/local/rbenv/shims/gem list | grep bundler
  ignore_errors: true
  register: bundler_installed

- name: rbenv | install bundler
  shell: RBENV_ROOT=${rbenv_root} /usr/local/rbenv/shims/gem install bundler && RBENV_ROOT=${rbenv_root} rbenv rehash
  when: not bundler_installed.stdout
